const assert = require('node:assert/strict');
const path = require('node:path');
const fs = require('node:fs');
const { pathToFileURL } = require('node:url');
const { chromium } = require('playwright');
const output = path.resolve('.tmp/legacy-games');
fs.mkdirSync(output, { recursive: true });
(async () => {
  const browser = await chromium.launch({ executablePath: process.env.BROWSER_PATH || 'C:/Program Files (x86)/Microsoft/Edge/Application/msedge.exe', headless: true });
  const context = await browser.newContext({ viewport: { width: 1366, height: 768 }, acceptDownloads: true });
  const page = await context.newPage();
  const errors = [];
  const external = [];
  const downloads = [];
  page.on('pageerror', (error) => errors.push(error.message));
  page.on('request', (request) => { if (/^https?:/.test(request.url())) external.push(request.url()); });
  page.on('download', (download) => downloads.push(download));
  const url = pathToFileURL(path.resolve('index.html')).href;
  await page.goto(url);
  const center = async (selector) => {
    const r = await page.locator(selector).first().boundingBox();
    assert.ok(r, selector + ' should be visible');
    return { x: r.x + r.width / 2, y: r.y + r.height / 2 };
  };
  const home = async (screen) => page.locator('#' + screen + '-screen [data-home]').click();
  const enter = async (name) => page.locator('[data-game="' + name + '"]').click();
  const count = () => page.locator('#fruit-count').textContent();
  const drag = async (fruit, basket, release = true) => {
    const a = await center(fruit), b = await center(basket);
    await page.mouse.move(a.x, a.y);
    await page.mouse.down();
    await page.mouse.move(b.x, b.y, { steps: 8 });
    if (release) await page.mouse.up();
  };
  await enter('fruit');
  await page.locator('.fruit-item').click();
  assert.equal(await count(), '0', 'Click alone never places fruit');
  await drag('.fruit-item', '#basket .basket-drop', false);
  await page.locator('.fruit-item').dispatchEvent('pointercancel');
  await page.mouse.up();
  assert.equal(await count(), '0', 'Cancelled drag must not count');
  assert.equal(await page.locator('.fruit-item.dragging').count(), 0);
  await drag('.fruit-item', '#basket .basket-drop', false);
  await page.keyboard.press('Escape');
  await page.mouse.up();
  assert.equal(await count(), '0', 'Escape cancels without progress');
  await drag('.fruit-item', '#basket .basket-drop');
  assert.equal(await count(), '1');
  await page.waitForTimeout(900);
  assert.equal(await page.locator('#fruit-lesson').textContent(), '先送一个', 'Prompt remains during celebration');
  assert.ok(await page.locator('#level-transition').isVisible());
  await page.waitForTimeout(2200);
  assert.equal(await page.locator('#fruit-lesson').textContent(), '再送几个');
  for (let i = 0; i < 3; i++) await drag('.fruit-item:not(:disabled)', '#basket .basket-drop');
  await page.waitForTimeout(900);
  assert.equal(await count(), '3');
  assert.equal(await page.locator('#fruit-lesson').textContent(), '再送几个', 'Rapid drops never skip levels');
  await page.waitForTimeout(3100);
  assert.equal(await page.locator('#fruit-lesson').textContent(), '送远一点');
  for (let i = 0; i < 3; i++) await drag('.fruit-item:not(:disabled)', '#basket .basket-drop');
  await page.waitForTimeout(3100);
  await page.screenshot({ path: path.join(output, 'fruit-sort.png'), fullPage: true });
  await drag('.fruit-item[data-fruit="apple"]', '#basket-pear .basket-drop');
  assert.equal(await count(), '0', 'Wrong kind returns to tray');
  for (const fruit of await page.locator('.fruit-item').all()) {
    const kind = await fruit.getAttribute('data-fruit');
    const r = await fruit.boundingBox(), b = await center(kind === 'pear' ? '#basket-pear .basket-drop' : '#basket .basket-drop');
    // Pick away from center; the object center, not the pointer, must land in the basket.
    await page.mouse.move(r.x + 15, r.y + 20);
    await page.mouse.down();
    await page.mouse.move(b.x - r.width / 2 + 15, b.y - r.height / 2 + 20, { steps: 6 });
    await page.mouse.up();
  }
  assert.equal(await count(), '4');
  assert.equal(await page.evaluate(() => localStorage.getItem('littleComputer.fruitRounds')), '1');
  assert.equal(await page.locator('.basket-contents svg').count(), 4);
  await home('fruit');
  await page.waitForTimeout(800);
  assert.ok(await page.locator('#home-screen').isVisible(), 'Exiting never gets redirected by a stale callback');
  await enter('fruit');
  await page.keyboard.press('Tab');
  await page.locator('.fruit-item').focus();
  await page.keyboard.press('Space');
  const ka = await center('.fruit-item'), kb = await center('#basket .basket-drop');
  for (let i = 0; i < Math.round(Math.abs(kb.x - ka.x) / 24); i++) await page.keyboard.press(kb.x > ka.x ? 'ArrowRight' : 'ArrowLeft');
  for (let i = 0; i < Math.round(Math.abs(kb.y - ka.y) / 24); i++) await page.keyboard.press(kb.y > ka.y ? 'ArrowDown' : 'ArrowUp');
  await page.keyboard.press('Space');
  assert.equal(await count(), '1', 'Keyboard drag places fruit');
  await home('fruit');

  await enter('stars');
  assert.equal(await page.locator('#star-target').textContent(), '3');
  await page.locator('.star-button:not(:disabled)').hover();
  assert.equal(await page.locator('#star-count').textContent(), '0');
  for (let i = 0; i < 3; i++) await page.locator('.star-button:not(:disabled)').click();
  assert.equal(await page.locator('.star-button.is-lit').count(), 3, 'Lit stars remain in the scene');
  assert.equal(await page.locator('#star-count').textContent(), '3');
  assert.ok(await page.locator('#stars-screen').isVisible());
  assert.equal(await page.evaluate(() => localStorage.getItem('littleComputer.starRounds')), '1');
  await page.screenshot({ path: path.join(output, 'stars-triangle.png'), fullPage: true });
  await home('stars');
  await page.evaluate(() => localStorage.setItem('littleComputer.settings', JSON.stringify({ starTarget: 10, fruitLevels: 2 })));
  await enter('stars');
  for (let i = 0; i < 3; i++) {
    await page.locator('.star-button:not(:disabled)').focus();
    await page.keyboard.press('Enter');
  }
  assert.equal(await page.evaluate(() => localStorage.getItem('littleComputer.starRounds')), '2');
  await page.waitForTimeout(1700);
  assert.equal(await page.locator('#star-count').textContent(), '0');
  assert.equal(await page.locator('#star-target').textContent(), '4', 'Pattern determines the number of stars, ignoring retired quantity settings');
  for (let i = 0; i < 4; i++) await page.locator('.star-button:not(:disabled)').click();
  assert.equal(await page.evaluate(() => localStorage.getItem('littleComputer.starRounds')), '3', 'Each completed pattern records once');
  await page.locator('#stars-screen [data-sound]').click();
  await home('stars');
  await enter('drawing');
  assert.equal(await page.locator('#drawing-screen [data-sound]').getAttribute('aria-pressed'), 'false', 'Mute follows across games');
  const snapshot = () => page.locator('#drawing-canvas').evaluate((canvas) => canvas.toDataURL());
  const line = async (dy = 0) => {
    const r = await page.locator('#drawing-canvas').boundingBox();
    await page.mouse.move(r.x + r.width * .2, r.y + r.height * .25 + dy);
    await page.mouse.down();
    await page.mouse.move(r.x + r.width * .45, r.y + r.height * .5 + dy, { steps: 15 });
    await page.mouse.move(r.x + r.width * .75, r.y + r.height * .3 + dy, { steps: 15 });
    await page.mouse.up();
  };
  const blank = await snapshot();
  await line();
  const first = await snapshot();
  assert.notEqual(first, blank);
  await page.locator('[data-color="#69aeca"]').click();
  await line(35);
  assert.notEqual(await snapshot(), first);
  await page.locator('#undo-drawing').click();
  assert.equal(await snapshot(), first, 'Undo restores exact previous bitmap');
  await home('drawing');
  await enter('drawing');
  assert.equal(await snapshot(), first, 'Leaving and returning preserves work');
  await page.reload();
  await enter('drawing');
  assert.equal(await snapshot(), first, 'Reload restores draft');
  await page.setViewportSize({ width: 1000, height: 800 });
  assert.equal(await snapshot(), first, 'Resize does not clear or resample bitmap');
  await page.setViewportSize({ width: 1366, height: 768 });
  await page.screenshot({ path: path.join(output, 'drawing-desk.png'), fullPage: true });
  await page.locator('#save-drawing').click();
  assert.ok(await page.locator('#drawing-finish-screen').isVisible());
  assert.equal(downloads.length, 0, 'Preview does not trigger download');
  assert.equal(await page.evaluate(() => localStorage.getItem('littleComputer.drawingCount')), '1');
  await page.locator('[data-drawing-replay]').click();
  await page.locator('#save-drawing').click();
  assert.equal(await page.evaluate(() => localStorage.getItem('littleComputer.drawingCount')), '1', 'Repeated preview does not inflate records');
  const waiting = page.waitForEvent('download');
  await page.locator('#export-drawing').click();
  const download = await waiting;
  await download.saveAs(path.join(output, 'drawing-export.png'));
  const png = fs.readFileSync(path.join(output, 'drawing-export.png'));
  assert.equal(png.readUInt32BE(16), 1600);
  assert.equal(png.readUInt32BE(20), 1000);
  await page.locator('#new-drawing').click();
  await page.locator('#cancel-clear').click();
  assert.equal(await snapshot(), first, 'Cancel new page preserves drawing');
  await page.locator('.drawing-more summary').click();
  await page.locator('#clear-drawing').click();
  await page.locator('#confirm-clear').click();
  assert.equal(await snapshot(), blank);
  await page.locator('#undo-drawing').click();
  assert.equal(await snapshot(), first, 'Changing paper can be undone');
  await page.locator('#drawing-canvas').focus();
  await page.keyboard.press('Space');
  await page.keyboard.press('ArrowRight');
  await page.keyboard.press('ArrowDown');
  await page.keyboard.press('Space');
  assert.notEqual(await snapshot(), first, 'Keyboard can draw a line');
  await page.evaluate(() => {
    const original = Storage.prototype.setItem;
    Storage.prototype.setItem = function (key, value) {
      if (key === 'littleComputer.drawingDraft') throw new DOMException('Full', 'QuotaExceededError');
      return original.call(this, key, value);
    };
  });
  await line(60);
  assert.match(await page.locator('#drawing-status').textContent(), /没能保存/);
  assert.ok(await page.locator('#save-drawing').isEnabled(), 'Storage failure keeps export available');
  await page.reload();
  for (const size of [{ width: 1920, height: 1080 }, { width: 768, height: 1024 }, { width: 390, height: 844 }, { width: 320, height: 740 }]) {
    await page.setViewportSize(size);
    for (const name of ['stars', 'fruit', 'drawing']) {
      await enter(name);
      assert.ok(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth), name + ' fits ' + size.width);
      if (size.width === 390) await page.screenshot({ path: path.join(output, name + '-mobile.png'), fullPage: true });
      await home(name);
    }
  }
  await page.emulateMedia({ reducedMotion: 'reduce' });
  await enter('stars');
  await page.locator('[data-demo="stars"]').click();
  assert.equal(await page.locator('#stars-screen .help-pointer').evaluate((el) => getComputedStyle(el).animationName), 'none');
  assert.deepEqual(errors, []);
  assert.deepEqual(external, []);
  await browser.close();
  console.log('PASS: fruit cancellation/rapid drops/classification/keyboard; star patterns/settings/keyboard; drawing undo/reentry/reload/resize/preview/export/clear/keyboard/quota; shared mute; four viewport sizes; reduced motion; offline.');
})().catch((error) => { console.error(error); process.exit(1); });
